name = "LIBSVMdata"
uuid = "e26130ba-f664-4e1e-a986-1cbf7dd5bec7"
authors = ["Theo Guyard"]
version = "0.1.5"

[deps]
AppDirs = "5a4fb9a2-b02d-4ffe-b178-6027dc2bc1ce"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1"
OrderedCollections = "1"
ProgressBars = "1"
AppDirs = "0.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
